export const PHONE = "9657316301";
export const PHONE_INTL = "+919657316301";

export const services = [
  { icon: "health", bgImage: "service-health.svg", hoverImage: "service-health.svg", title: { en: "Wellness Advisor", mr: "आरोग्य सल्लागार" }, desc: { en: "Personalized diet, exercise, and lifestyle guidance tailored to your body.", mr: "योग्य आहार, व्यायाम आणि जीवनशैली मार्गदर्शक — तुमच्या शरीराला अनुरूप असा सर्वांगीण आरोग्य आराखडा." }, tag: { en: "Wellness", mr: "आरोग्य" } },
  { icon: "finance", bgImage: "service-finance.svg", hoverImage: "service-finance.svg", title: { en: "Financial Planner", mr: "आर्थिक नियोजक" }, desc: { en: "Investment, savings, and financial stability planning based on your income and goals.", mr: "गुंतवणूक, बचत आणि आर्थिक स्थैर्य — उत्पन्नानुसार शिस्तबद्ध व सुरक्षित संपत्ती नियोजन." }, tag: { en: "Finance", mr: "वित्त" } },
  { icon: "numerology", bgImage: "service-numerology.svg", hoverImage: "service-numerology.svg", title: { en: "Numerologist", mr: "अंकशास्त्रज्ञ" }, desc: { en: "Birth-date-based guidance for career, naming, and important life decisions.", mr: "जन्मतारखेनुसार योग्य मार्गदर्शन — करिअर, नाव व महत्त्वाच्या निर्णयांसाठी अंकशास्त्रीय विश्लेषण." }, tag: { en: "Numerology", mr: "अंकशास्त्र" } },
  { icon: "crystal", bgImage: "service-crystal.svg", hoverImage: "service-crystal.svg", title: { en: "Crystal Healer", mr: "क्रिस्टल हीलर" }, desc: { en: "Energy balance and mental calmness through natural crystals and healing practices.", mr: "ऊर्जा संतुलन आणि मानसिक शांतता — नैसर्गिक स्फटिकांच्या मदतीने सकारात्मक ऊर्जेचा प्रवाह." }, tag: { en: "Healing", mr: "उपचार" } },
  { icon: "vastu", bgImage: "service-vastu.svg", hoverImage: "service-vastu.svg", title: { en: "Vastu Expert", mr: "वास्तुशास्त्र तज्ज्ञ" }, desc: { en: "Home and workplace remedies for prosperity, positivity, and better flow of energy.", mr: "घर आणि कार्यस्थळासाठी वास्तू उपाय — समृद्धी व सौख्यासाठी योग्य दिशा व रचना मार्गदर्शन." }, tag: { en: "Vastu", mr: "वास्तु" } },
  { icon: "mind", bgImage: "service-mind.svg", hoverImage: "service-mind.svg", title: { en: "Psychological Counselor", mr: "मानसशास्त्रीय समुपदेशक" }, desc: { en: "Stress relief and emotional support through professional counseling sessions.", mr: "तणाव मुक्ती आणि भावनिक आधार — मन:शांतीसाठी व्यावसायिक समुपदेशन सत्रे." }, tag: { en: "Counseling", mr: "समुपदेशन" } },
];

export const audience = [
  { icon: "people", bgImage: "service-finance.svg", title: { en: "Working Professionals", mr: "नोकरी करणारे व्यावसायिक" }, points: [{ en: "Extra income opportunity", mr: "अतिरिक्त उत्पन्नाची संधी" }, { en: "Flexible timing", mr: "लवचिक वेळ" }, { en: "Career growth potential", mr: "करिअर वाढीची संधी" }] },
  { icon: "shield", bgImage: "service-health.svg", title: { en: "Doctors", mr: "डॉक्टर्स" }, points: [{ en: "Opportunity to guide patients financially", mr: "रुग्णांसाठी आर्थिक दृष्ट्या मार्गदर्शनाची संधी" }, { en: "Good income with strong reputation", mr: "प्रतिष्ठेसोबत चांगले उत्पन्न" }] },
  { icon: "clock", bgImage: "service-mind.svg", title: { en: "Teachers / Professors", mr: "शिक्षक / प्राध्यापक" }, points: [{ en: "Additional income alongside a stable job", mr: "स्थिर नोकरीसह अतिरिक्त उत्पन्न" }, { en: "Spread financial awareness in society", mr: "समाजात आर्थिक जागरूकता निर्माण" }] },
  { icon: "chart", bgImage: "service-numerology.svg", title: { en: "CA / Lawyers / Consultants", mr: "CA / वकील / कन्सल्टंट्स" }, points: [{ en: "Value-added services for clients", mr: "क्लायंटसाठी मूल्यवर्धित सेवा" }, { en: "Referral-based earning potential", mr: "रेफरल आधारित चांगले उत्पन्न" }] },
  { icon: "home", bgImage: "service-vastu.svg", title: { en: "Homemakers", mr: "गृहिणी" }, points: [{ en: "Affordable self-start career option", mr: "परवडणारी स्वतःची करिअर सुरुवात" }, { en: "Opportunity for financial independence", mr: "आर्थिक स्वावलंबनाची संधी" }] },
  { icon: "briefcase", bgImage: "service-crystal.svg", title: { en: "Business Owners / Self-employed", mr: "व्यावसायिक / स्वयंरोजगार" }, points: [{ en: "Extra income alongside business", mr: "व्यवसायासोबत अतिरिक्त उत्पन्न" }, { en: "Become a financial planning specialist", mr: "आर्थिक नियोजन तज्ञ बना" }] },
  { icon: "trophy", bgImage: "service-finance.svg", title: { en: "Retired Professionals", mr: "निवृत्त कर्मचारी" }, points: [{ en: "Use your experience wisely", mr: "अनुभवाचा योग्य उपयोग" }, { en: "Stable and respected additional income", mr: "स्थिर आणि सन्माननीय अतिरिक्त उत्पन्न" }] },
];

export const features = [
  { icon: "clock", title: { en: "Flexible work hours", mr: "लवचिक कामाचे तास" }, desc: { en: "Full freedom to work according to your own schedule.", mr: "आपल्या वेळेनुसार काम करण्याचे पूर्ण स्वातंत्र्य." } },
  { icon: "chart", title: { en: "Unlimited income opportunities", mr: "उत्पन्नाच्या अमर्यादित संधी" }, desc: { en: "Performance-based opportunities — direct rewards for effort.", mr: "परफॉर्मन्स आधारित संधी — मेहनतीचे थेट फळ." } },
  { icon: "people", title: { en: "Professional training and continuous guidance", mr: "व्यावसायिक प्रशिक्षण व सतत मार्गदर्शन" }, desc: { en: "Support at every stage from the very beginning.", mr: "सुरुवातीपासून प्रत्येक टप्प्यावर सहकार्य." } },
  { icon: "trophy", title: { en: "Great career growth opportunities", mr: "करिअर वाढीच्या उत्तम संधी" }, desc: { en: "A clear and performance-based career path.", mr: "स्पष्ट व परफॉर्मन्स आधारित करिअर मार्ग." } },
  { icon: "shield", title: { en: "Solutions that bring financial security", mr: "लोकांना आर्थिक सुरक्षिततेकडे नेण्याचे समाधान" }, desc: { en: "Work that helps secure the future of others.", mr: "इतरांचे भविष्य सुरक्षित करण्याचे काम." } },
  { icon: "check", title: { en: "Reputation, recognition, and personal fulfillment", mr: "प्रतिष्ठा, ओळख आणि आत्मिक समाधान" }, desc: { en: "A respected and meaningful identity in society.", mr: "समाजात आदरयुक्त व अर्थपूर्ण ओळख." } },
];

export const faqs = [
  { q: { en: "What is a free information session?", mr: "मोफत माहिती सत्र म्हणजे काय?" }, a: { en: "It is a short 20-minute session where we explain how to become a Financial Planner, the work process, training support, and income structure based on performance. There is no obligation — just learn and decide.", mr: "हे फक्त 20 मिनिटांचे सत्र आहे — यात Financial Planner कसे व्हावे, कामाची पद्धत, प्रशिक्षण-सपोर्ट आणि उत्पन्नाची रचना (परफॉर्मन्स आधारित) समजावून सांगितली जाते. कोणतेही बंधन नाही, फक्त माहिती घ्या आणि निर्णय घ्या." } },
  { q: { en: "How do I book a service appointment?", mr: "सेवांसाठी अपॉइंटमेंट कशी घ्यावी?" }, a: { en: "Click the 'Call for Free Advice' button below or contact us directly at 9657316301 via call or WhatsApp.", mr: "खालील 'मोफत सल्ल्यासाठी कॉल करा' बटणावर क्लिक करा किंवा 9657316301 या क्रमांकावर थेट कॉल / व्हॉट्सअ‍ॅप करा." } },
  { q: { en: "Can all services be availed from one place?", mr: "सर्व सेवा एकाच व्यक्तीकडून मिळतात का?" }, a: { en: "Yes. Under DINAKO Multi Solutions, health, financial planning, numerology, crystal healing, vastu, and psychological counseling are available under one roof.", mr: "होय, DINAKO Multi Solutions अंतर्गत आरोग्य, आर्थिक नियोजन, अंकशास्त्र, क्रिस्टल हीलिंग, वास्तुशास्त्र व मानसशास्त्रीय समुपदेशन या सर्व सेवा एकाच छताखाली उपलब्ध आहेत." } },
  { q: { en: "Is prior experience required to become a Financial Planner?", mr: "Financial Planner बनण्यासाठी अनुभव आवश्यक आहे का?" }, a: { en: "No. Detailed training and guidance are provided at every stage, and people from any background can participate.", mr: "नाही. प्रत्येक टप्प्यावर सखोल प्रशिक्षण व मार्गदर्शन दिले जाते — कोणत्याही पार्श्वभूमीच्या व्यक्ती सहभागी होऊ शकतात." } },
];
